In [1]:
import sqlite3

In [4]:
conn=sqlite3.connect('wildlife.db')
cursor=conn.cursor()

In [25]:
#Created database

cursor.execute("""CREATE TABLE IF NOT EXISTS animals (
                AnimalID INTEGER PRIMARY KEY AUTOINCREMENT,
                CommonName TEXT,
                ScientificName TEXT,
                Habitat TEXT,
                Longevity INTEGER
               )""")

cursor.execute("""CREATE TABLE IF NOT EXISTS sightings (
                SightingID INTEGER PRIMARY KEY AUTOINCREMENT, 
                AnimalID INTEGER,
                LocationID INTEGER, 
                Date DATETYPE,
                Time TIMESTAMP,
                ObserverName TEXT,
                Notes TEXT
               )""")

cursor.execute("""CREATE TABLE IF NOT EXISTS locations (
                LocationID INTEGER PRIMARY KEY AUTOINCREMENT,
                Name TEXT,
                Latitude REAL,
                Longitude REAL,
                Region TEXT
               )""")

conn.commit()

In [15]:
#Inserted values INTO animals table
cursor.execute(""" INSERT INTO animals (CommonName,ScientificName,Habitat,Longevity) VALUES
                ('African Elephant', 'Loxodonta africana', 'Savannah', 60),
                ('Bald Eagle', 'Haliaeetus leucocephalus', 'Forests, Lakes', 20),
                ('Bengal Tiger', 'Panthera tigris tigris', 'Tropical Forest', 15),
                ('Blue Whale', 'Balaenoptera musculus', 'Oceans', 70),
                ('Giant Panda', 'Ailuropoda melanoleuca', 'Bamboo Forest', 20),
                ('Polar Bear', 'Ursus maritimus', 'Arctic', 25),
                ('Giraffe', 'Giraffa camelopardalis', 'Savannah', 25),
                ('Great White Shark', 'Carcharodon carcharias', 'Oceans', 30),
                ('Koala', 'Phascolarctos cinereus', 'Eucalyptus Forest', 10),
                ('Red Fox', 'Vulpes vulpes', 'Forest, Grassland', 10),
                ('Siberian Tiger', 'Panthera tigris altaica', 'Taiga', 15),
                ('Kangaroo', 'Macropus rufus', 'Grassland', 6),
                ('African Lion', 'Panthera leo', 'Savannah', 15),
                ('American Bison', 'Bison bison', 'Grassland', 20)""")
conn.commit()

In [26]:
#Inserted values INTO sightings table
cursor.execute(""" INSERT INTO sightings (AnimalID, LocationID, Date, Time, ObserverName, Notes) VALUES
(1, 1, '2023-07-21', '10:15:00', 'Alice Johnson', 'Observed near the river'),
(1, 2, '2023-07-22', '11:30:00', 'Bob Smith', 'Grazing in the savannah'),
(1, 3, '2023-07-23', '12:45:00', 'Carol White', 'Drinking water'),
(1, 4, '2023-07-24', '14:00:00', 'David Brown', 'Playing with others'),
(1, 5, '2023-07-25', '15:15:00', 'Emily Davis', 'Wandering through the grass'),
(2, 6, '2023-07-26', '08:30:00', 'Frank Wilson', 'Soaring high above'),
(2, 7, '2023-07-27', '09:45:00', 'Grace Thompson', 'Perched on a tree'),
(2, 8, '2023-07-28', '11:00:00', 'Henry Garcia', 'Hunting for fish'),
(2, 9, '2023-07-29', '13:15:00', 'Ivy Martinez', 'In flight over the lake'),
(3, 10, '2023-07-30', '16:20:00', 'Jack Anderson', 'Stalking through the forest'),
(3, 11, '2023-07-31', '17:35:00', 'Kathy Roberts', 'Resting in the shade'),
(3, 12, '2023-08-01', '19:10:00', 'Larry Clark', 'Roaring at sunset'),
(3, 13, '2023-08-02', '20:50:00', 'Mary Lewis', 'Prowling quietly'),
(3, 14, '2023-08-03', '22:05:00', 'Nancy Lee', 'Marking territory'),
(4, 15, '2023-08-04', '23:20:00', 'Oscar Walker', 'Breaching the surface'),
(4, 16, '2023-08-05', '00:35:00', 'Paul Hall', 'Feeding in the deep'),
(4, 17, '2023-08-06', '01:50:00', 'Quincy Allen', 'Swimming in the ocean'),
(4, 18, '2023-08-07', '03:05:00', 'Rachel Young', 'Singing songs'),
(4, 19, '2023-08-08', '04:20:00', 'Samuel Hernandez', 'Spouting water'),
(5, 20, '2023-08-09', '05:35:00', 'Tina King', 'Feeding on bamboo'),
(5, 21, '2023-08-10', '06:50:00', 'Uma Scott', 'Resting in the forest'),
(5, 22, '2023-08-11', '08:05:00', 'Victor Adams', 'Climbing a tree'),
(5, 23, '2023-08-12', '09:20:00', 'Wendy Baker', 'Playing with cubs'),
(5, 24, '2023-08-13', '10:35:00', 'Xander Carter', 'Wandering around'),
(6, 25, '2023-08-14', '11:50:00', 'Yvonne Diaz', 'Walking on ice'),
(6, 26, '2023-08-15', '13:05:00', 'Zachary Evans', 'Swimming in the sea'),
(6, 27, '2023-08-16', '14:20:00', 'Amanda Fisher', 'Hunting for seals'),
(6, 28, '2023-08-17', '15:35:00', 'Brian Green', 'Resting on a glacier'),
(6, 29, '2023-08-18', '16:50:00', 'Clara Harris', 'Playing in the snow'),
(7, 30, '2023-08-19', '18:05:00', 'Derek Johnson', 'Eating leaves from a tree'),
(7, 31, '2023-08-20', '19:20:00', 'Ella Kelly', 'Walking gracefully'),
(7, 32, '2023-08-21', '20:35:00', 'Fiona Lewis', 'Grazing in the savannah'),
(7, 33, '2023-08-22', '21:50:00', 'George Miller', 'Resting under a tree'),
(8, 34, '2023-08-23', '22:05:00', 'Hannah Nelson', 'Swimming near the reef'),
(8, 35, '2023-08-24', '23:20:00', 'Ian Owens', 'Hunting in deep water'),
(8, 36, '2023-08-25', '00:35:00', 'Julia Perez', 'Patrolling the coast'),
(8, 37, '2023-08-26', '01:50:00', 'Kevin Ramirez', 'Feeding on seals'),
(9, 38, '2023-08-27', '02:05:00', 'Laura Sanchez', 'Sleeping in a eucalyptus tree'),
(9, 39, '2023-08-28', '03:20:00', 'Michael Turner', 'Eating eucalyptus leaves'),
(9, 40, '2023-08-29', '04:35:00', 'Nina Underwood', 'Climbing slowly'),
(10, 41, '2023-08-30', '05:50:00', 'Oliver Vance', 'Hunting in the forest'),
(10, 42, '2023-08-31', '07:05:00', 'Peter White', 'Exploring the grasslands'),
(10, 43, '2023-09-01', '08:20:00', 'Quinn Xiong', 'Resting in the underbrush'),
(11, 44, '2023-09-02', '09:35:00', 'Rose Young', 'Stalking in the snow'),
(11, 45, '2023-09-03', '10:50:00', 'Sam Zane', 'Roaring in the distance'),
(12, 46, '2023-09-04', '11:05:00', 'Tina Abbott', 'Hopping across the grasslands'),
(12, 47, '2023-09-05', '12:20:00', 'Umar Bell', 'Grazing on shrubs'),
(13, 48, '2023-09-06', '13:35:00', 'Violet Carter', 'Resting under a tree'),
(13, 49, '2023-09-07', '14:50:00', 'Walter Davis', 'Roaring at sunset'),
(14, 50, '2023-09-08', '16:05:00', 'Xena Evans', 'Grazing in the open plains')
               """)
conn.commit()

In [23]:
# cursor.execute("DROP TABLE IF EXISTS animals")
cursor.execute("DROP TABLE IF EXISTS sightings")
conn.commit()

In [17]:
#Inserted values INTO location table
conn.execute("""INSERT INTO locations (Name, Latitude, Longitude, Region) VALUES
('Savannah Area', -1.957875, 37.297206, 'Africa'),
('Forest Region', 45.923123, -66.641354, 'North America'),
('Tropical Forest Zone', 23.634501, -102.552784, 'Asia'),
('Oceanic Zone', 0.000000, -140.000000, 'Pacific Ocean'),
('Bamboo Forest', 30.153360, 103.991530, 'China'),
('Arctic Zone', 70.299150, -43.994855, 'Arctic'),
('Grassland Savannah', -15.644258, 17.626501, 'Africa'),
('Coastal Ocean', -34.603684, -58.381559, 'South America'),
('Eucalyptus Forest', -33.868820, 151.209290, 'Australia'),
('Mixed Forest Area', 48.379433, 31.165580, 'Europe'),
('Taiga Zone', 61.524010, 105.318756, 'Russia'),
('Grassland Zone', -25.274398, 133.775136, 'Australia'),
('African Savannah', -8.783195, 34.508523, 'Africa'),
('North American Grassland', 39.011902, -98.484246, 'North America'),
('Oceanic Region', 19.896766, -155.582782, 'Pacific Ocean'),
('Mountain Region', 35.907757, 127.766922, 'Asia'),
('Grassland Area', 1.352083, 103.819836, 'Asia'),
('Forest and Tundra', 60.472024, 8.468946, 'Europe'),
('Rainforest Zone', -3.465305, -62.215881, 'South America'),
('Woodland Area', 55.378051, -3.435973, 'United Kingdom'),
('Rainforest Region', -3.373056, -65.856665, 'South America'),
('Tropical Forest Area', -1.940278, 29.873888, 'Africa'),
('Tropical Forest Habitat', 15.870032, 100.992541, 'Thailand'),
('Bamboo Forest Area', 29.760427, -95.369803, 'United States'),
('Mixed Grassland', 46.603354, 1.888334, 'France'),
('Savannah Zone', -2.154007, 37.045129, 'Africa'),
('Forest Shade', 35.861660, 104.195397, 'China'),
('Forest Prowl', 61.013710, 99.196396, 'Russia'),
('Swimming Surface', 34.052234, -118.243685, 'United States'),
('Fresh Bamboo', 22.396428, 114.109497, 'Hong Kong'),
('Snowy Play Area', 60.128161, 18.643501, 'Sweden'),
('Leafy Eats', 52.132633, 5.291266, 'Netherlands'),
('Shore Patrol', -36.848460, 174.763332, 'New Zealand'),
('Sleeping Branch', 37.774929, -122.419416, 'United States'),
('Small Prey Stalk', 55.755826, 37.617300, 'Russia'),
('Hopping Zone', 38.907192, -77.036871, 'United States'),
('Grazing Grassland', 40.463667, -3.749220, 'Spain'),
('Near River Grazing', 46.603354, 1.888334, 'France'),
('Breaching Zone', 19.896766, -155.582782, 'Hawaii'),
('Cliff Climb', 35.907757, 127.766922, 'South Korea'),
('Running Fast Area', 1.352083, 103.819836, 'Singapore'),
('Howling Forest', 60.472024, 8.468946, 'Norway'),
('Tree Swinging', -3.465305, -62.215881, 'Brazil'),
('Bush Hideout', 55.378051, -3.435973, 'United Kingdom'),
('Jungle Explorer', -3.373056, -65.856665, 'Colombia'),
('Leaf Eating Area', -1.940278, 29.873888, 'Rwanda'),
('Quick Flying', 15.870032, 100.992541, 'Thailand'),
('Bamboo Climbing', 29.760427, -95.369803, 'Texas, USA'),
('Savannah Run', 46.603354, 1.888334, 'France'),
('Tree Climb', -2.154007, 37.045129, 'Kenya'),
('Waterhole Rest', 35.861660, 104.195397, 'China'),
('Tree Shade', 61.013710, 99.196396, 'Siberia'),
('Prowl Area', 34.052234, -118.243685, 'Los Angeles, USA'),
('Swimming Near Surface', 22.396428, 114.109497, 'Hong Kong'),
('Fresh Bamboo Area', 60.128161, 18.643501, 'Sweden'),
('Snowy Play Area', 52.132633, 5.291266, 'Netherlands'),
('Shore Patrol', -36.848460, 174.763332, 'New Zealand'),
('Branch Sleeping', 37.774929, -122.419416, 'San Francisco, USA'),
('Stalking Zone', 55.755826, 37.617300, 'Moscow, Russia'),
('Hopping Ground', 38.907192, -77.036871, 'Washington, D.C., USA'),
('Grassland Grazing', 40.463667, -3.749220, 'Spain')""")
conn.commit()